version: '3.2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=new_vesrion
    image: web-py:new_version
    ports:
      - "8001:5000"
     
  redis:
    image: "redis:latest"
