version: '3.2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - COMMIT_ID=$(git rev-parse --short HEAD)
    image: web-py:${COMMIT_ID}
    ports:
      - "8001:5000"
     
  redis:
    image: "redis:latest"
