version: '3.2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=`date +'%H.%M'`
    image: web-py:${VERSION}
    ports:
      - "8001:5000"
     
  redis:
    image: "redis:latest"
