version: '3.2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: web-py:latest
    pull_policy: build
    ports:
      - "8001:5000"
     
  redis:
    image: "redis:latest"
