---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 15
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: nginxdemos/hello
        name: hello-world
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "124Mi"
        ports:
        - containerPort: 80
          protocol: TCP
          name: hello-world
